<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>figure_MAC Studio Fix Fluid SPF 154250034000</name>
   <tag></tag>
   <elementGuidId>0f29a001-bc54-4315-a808-46a5ff109a3a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='carouselNo-1']/div[2]/div[2]/div/div[8]/div/div/a/figure</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>figure</value>
      <webElementGuid>3ba150f9-50d2-4924-a255-dc5632d2a3bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>card m-card ma-figure</value>
      <webElementGuid>ace513ec-a2da-4666-8bfb-6df30a8acea5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> M·A·C Studio Fix Fluid SPF 15$42500$34000</value>
      <webElementGuid>7555665d-52a7-437e-ac86-bc3c18ce3fe6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;carouselNo-1&quot;)/div[@class=&quot;slick-slider slick-initialized&quot;]/div[@class=&quot;slick-list&quot;]/div[@class=&quot;slick-track&quot;]/div[@class=&quot;slick-slide slick-active&quot;]/div[1]/div[@class=&quot;item&quot;]/a[1]/figure[@class=&quot;card m-card ma-figure&quot;]</value>
      <webElementGuid>05672b47-a449-4d17-9858-b350370efa38</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='carouselNo-1']/div[2]/div[2]/div/div[8]/div/div/a/figure</value>
      <webElementGuid>72fed205-c60d-41e3-975a-622a9e76d09f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ver más'])[1]/following::figure[8]</value>
      <webElementGuid>21d42534-d239-4724-b5ec-46799c5675a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Moda hombre hasta 20% de descuento'])[1]/following::figure[8]</value>
      <webElementGuid>a2230b50-9014-4a43-b25b-583f5a856491</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Muebles para bebés'])[1]/preceding::figure[33]</value>
      <webElementGuid>e6c56a95-8813-4c7a-bf67-cfe7bb30f5e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/div/a/figure</value>
      <webElementGuid>9d4da99a-10e3-4bfc-a1e6-379c5585462a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//figure[(text() = ' M·A·C Studio Fix Fluid SPF 15$42500$34000' or . = ' M·A·C Studio Fix Fluid SPF 15$42500$34000')]</value>
      <webElementGuid>5441b073-ffbb-4f0f-8138-bedafe0d9166</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
