<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ul_12345</name>
   <tag></tag>
   <elementGuidId>804b3a0b-272f-4142-8243-efc8402852e1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='carouselNo-1']/div[2]/ul</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>ul.slick-dots</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>ul</value>
      <webElementGuid>84ed881a-0aa8-4efe-b03e-d4fcb4ffcc66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>slick-dots</value>
      <webElementGuid>4843b875-2668-49c7-8ad9-912b9c8ce288</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>12345</value>
      <webElementGuid>14839ad7-110e-4e2b-a1e8-ef77e6f91e3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;carouselNo-1&quot;)/div[@class=&quot;slick-slider slick-initialized&quot;]/ul[@class=&quot;slick-dots&quot;]</value>
      <webElementGuid>879ecf40-1d99-41c0-b9c4-23fde9ceca66</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='carouselNo-1']/div[2]/ul</value>
      <webElementGuid>6d2363f1-6440-4c9e-bb32-7bfaed23c7fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ver más'])[1]/following::ul[1]</value>
      <webElementGuid>ed939faa-7689-4ef2-9cfc-503f043c6abf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Moda hombre hasta 20% de descuento'])[1]/following::ul[1]</value>
      <webElementGuid>ca60b372-d511-41ff-bf11-5eb99ce627a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Muebles para bebés'])[1]/preceding::ul[1]</value>
      <webElementGuid>6d830295-6262-4b42-8f63-b4ef51156278</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/ul</value>
      <webElementGuid>f019d50a-3235-40f3-be5b-6172e895fd74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//ul[(text() = '12345' or . = '12345')]</value>
      <webElementGuid>8948b676-2804-451d-b18e-23a105f1fb5b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
