<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Inicia sesin_header_logo liverpool</name>
   <tag></tag>
   <elementGuidId>3e580ec6-1282-40a9-9c9f-40b0bfd6c75f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.header_logo.liverpool</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@alt='liverpool']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>1346ef47-8645-41fe-9ead-23cd0b6e0f9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://assetspwa.liverpool.com.mx/assets/images/emails/facebook/logo.png</value>
      <webElementGuid>d9686aca-e4aa-4b16-93bf-bf5dfca2d3c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>header_logo liverpool</value>
      <webElementGuid>5c3932b6-a9ba-4657-9f2c-485f0ef8927b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>liverpool</value>
      <webElementGuid>2360e26d-91e2-40b3-b4dd-de0565303e06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>liverpool</value>
      <webElementGuid>f6a8ccb7-6a87-4047-b034-53219947deb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;_widget-auto-layout _hide-prompt-logo&quot;]/header[@class=&quot;header liverpool&quot;]/a[1]/img[@class=&quot;header_logo liverpool&quot;]</value>
      <webElementGuid>c9269807-c57f-4045-8598-7042ca5f64d6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='liverpool']</value>
      <webElementGuid>75e22240-d7d2-459b-8568-ccc4c49a441c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>396844a0-7711-4770-ae44-5c92f3d8fc6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://assetspwa.liverpool.com.mx/assets/images/emails/facebook/logo.png' and @alt = 'liverpool' and @title = 'liverpool']</value>
      <webElementGuid>e2eacf20-8bdd-41ce-b8f5-dd794be59efa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
