<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Crear cuenta</name>
   <tag></tag>
   <elementGuidId>9907dfc9-ce09-4cf3-a614-5f322d6fb469</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button[name=&quot;action&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@name='action']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>22b97f10-81f8-46e3-ab98-ba8f06e5f4b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>25fae56c-3a6e-4be2-ba9a-b3541f5c21d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>action</value>
      <webElementGuid>b4503b59-b440-40cb-9336-308eb72a4991</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>default</value>
      <webElementGuid>7d6227db-124b-4fb8-9f85-2763ebcd8926</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>c818c634d cab70d39b c9fec752d c570086c6 c696779d3</value>
      <webElementGuid>a1a3e738-168c-4f55-8692-d7daceb477a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Crear cuenta</value>
      <webElementGuid>21460862-073d-4eea-b856-b012fbb3175c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;_widget-auto-layout _hide-prompt-logo&quot;]/main[@class=&quot;_widget c9d5d442b&quot;]/section[@class=&quot;c816e925e _prompt-box-outer cfabdf962&quot;]/div[@class=&quot;c41b10a9e c5d6300a1&quot;]/div[@class=&quot;c37260841&quot;]/div[@class=&quot;cd2091297 c66a28951&quot;]/form[@class=&quot;c343a2ca4 c15ff9a9f&quot;]/div[@class=&quot;c93926433&quot;]/button[@class=&quot;c818c634d cab70d39b c9fec752d c570086c6 c696779d3&quot;]</value>
      <webElementGuid>466da04f-dca9-4b33-b40e-f472ee9b8705</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@name='action']</value>
      <webElementGuid>30b74b44-1921-4f2c-aa07-29449bbd22f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Números (0-9)'])[1]/following::button[1]</value>
      <webElementGuid>e8ea1379-fb8f-4d10-a927-f7d2e8e6122d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Letras mayúsculas (A-Z)'])[1]/following::button[1]</value>
      <webElementGuid>a37d9233-d8da-42b3-9fbb-7184993a3ab2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Inicia sesión'])[1]/preceding::button[1]</value>
      <webElementGuid>37c30648-3e76-4bf3-9094-e2cda15f2f2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='O'])[1]/preceding::button[1]</value>
      <webElementGuid>6257be53-c031-43b0-9f3b-d6e2487cbaf1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button</value>
      <webElementGuid>519544f6-59f9-404e-a86a-17a44949eede</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and @name = 'action' and (text() = 'Crear cuenta' or . = 'Crear cuenta')]</value>
      <webElementGuid>45e290ba-9286-406c-811c-f7ce1b7ff9a7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
