<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img__mainBanner</name>
   <tag></tag>
   <elementGuidId>81eb707a-6006-4fba-9b75-2dcc15053e24</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mainBanner</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='mainBanner']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>8bd7e159-d5a3-4c47-ab14-2d9db0c1bfd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mainBanner</value>
      <webElementGuid>9c039436-80cc-4af0-a042-e5495716099a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-mainBanner__image lazyloaded</value>
      <webElementGuid>e581f73f-f71a-4e4a-ac59-983678cdaac3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-src</name>
      <type>Main</type>
      <value>https://assetspwa.liverpool.com.mx/assets/digital/home/img/ago21/bc1_230821mue.jpg</value>
      <webElementGuid>ad63a2a7-532b-4afd-9569-13d8d755eae3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Muebles, Sillones, Sillas,  Exterior, Salas, Recámaras | Liverpool</value>
      <webElementGuid>b947e09e-bbeb-4ca1-b40b-36c80f2aa859</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Muebles | Liverpool</value>
      <webElementGuid>561c0f9a-d6ea-40c6-a4ab-e035e9fcd622</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://assetspwa.liverpool.com.mx/assets/digital/home/img/ago21/bc1_230821mue.jpg</value>
      <webElementGuid>4b6cb5c7-beb6-41ce-b7e4-d23b4afc571b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bannerNo-1&quot;)/div[@class=&quot;container-fluid p-0&quot;]/section[@class=&quot;o-mainBanner row&quot;]/div[@class=&quot;col-12 col-lg-12&quot;]/div[@class=&quot;m-banners-outpadd nop&quot;]/a[@class=&quot;m-mainBanner__link&quot;]/picture[@class=&quot;m-mainBanner__picture&quot;]/img[@id=&quot;mainBanner&quot;]</value>
      <webElementGuid>2023b813-12bd-44dc-950b-c7979cf6a5a5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='mainBanner']</value>
      <webElementGuid>54c57342-20f2-4bc9-9b33-e1f1cf7f85c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='bannerNo-1']/div[2]/section/div/div/a/picture/img</value>
      <webElementGuid>58868445-5de3-4a4f-9476-60416950f0da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Muebles, Sillones, Sillas,  Exterior, Salas, Recámaras | Liverpool']</value>
      <webElementGuid>6d4f267a-99f2-493f-8f5e-4cbe55e78927</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//picture/img</value>
      <webElementGuid>9dfceb1e-4c30-4297-bd05-2c7e05ba35e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@id = 'mainBanner' and @alt = 'Muebles, Sillones, Sillas,  Exterior, Salas, Recámaras | Liverpool' and @title = 'Muebles | Liverpool' and @src = 'https://assetspwa.liverpool.com.mx/assets/digital/home/img/ago21/bc1_230821mue.jpg']</value>
      <webElementGuid>84ce8b1f-216f-400d-a366-dff40ffc68c7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
