<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_</name>
   <tag></tag>
   <elementGuidId>381adc00-2ce4-41c1-9e9d-384b1a55dd77</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.row.d-none.d-lg-block.m-row-bootstrap</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/div/div/div[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>09ccb421-089c-4b64-b253-475c1106fac5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>row d-none d-lg-block m-row-bootstrap</value>
      <webElementGuid>29e45790-0c89-45e0-81ff-ce02dd03de97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>‌ </value>
      <webElementGuid>507ee91d-6592-49fb-b16b-c777ccb08171</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;min-vh-100&quot;]/div[@class=&quot;container-fluid o-main-container p-0 o-plp-secondaryContainer&quot;]/div[@class=&quot;container o-container__secondary search---&quot;]/div[@class=&quot;row d-none d-lg-block m-row-bootstrap&quot;]</value>
      <webElementGuid>e4081c38-c842-45dd-9b24-b388be384e6f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/div/div[3]</value>
      <webElementGuid>04195d14-252b-4481-8ee8-82fb41575fca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Filtrar'])[1]/following::div[3]</value>
      <webElementGuid>593610ec-6979-4514-b4f0-eb32e0508e1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Más vendido'])[1]/following::div[5]</value>
      <webElementGuid>e158e887-59aa-4ef4-a5ba-a8dcfbef039e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='‌'])[2]/preceding::div[4]</value>
      <webElementGuid>fa85d307-ee9d-41c2-a047-9c3661f88020</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div[3]</value>
      <webElementGuid>ad245597-ee04-4704-b6eb-37b88fc2e2f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '‌ ' or . = '‌ ')]</value>
      <webElementGuid>a7e2d37f-dfde-459a-9f9a-01891f63ff0f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
