<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Ordenar por</name>
   <tag></tag>
   <elementGuidId>90187ab4-2d08-48b8-86b3-dd86fc023bfd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.col-lg-4.col-xl-3.mb-4.pr-2.pl-0 > div.m-dropdown > div.dropdown > #sortby</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//a[@id='sortby'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>a409aa29-755b-4e07-9928-c3544f8bb1f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn dropdown-toggle sortBy</value>
      <webElementGuid>00d6eb53-84a0-40ec-ae08-3985949cb4c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>sortby</value>
      <webElementGuid>e6e4ab79-20be-4d76-b2f8-23cdfa31072f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/tienda?s=vaso#!</value>
      <webElementGuid>2cd1491d-1aeb-4080-a26c-231004fc6803</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Ordenar por:</value>
      <webElementGuid>a9bade8f-ccc9-41e6-a4cd-41514b8c5a23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;min-vh-100&quot;]/div[@class=&quot;container-fluid o-main-container p-0 o-plp-secondaryContainer&quot;]/div[@class=&quot;container o-container__secondary search---&quot;]/div[@class=&quot;row mt-lg-3 m-row-bootstrap&quot;]/main[@class=&quot;col-lg-9 m-column_mainContent&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-12 d-none d-lg-block pr-1 pr-1 pl-lg-1 pr-lg-1&quot;]/div[@class=&quot;d-flex align-items-center&quot;]/div[@class=&quot;col-lg-4 col-xl-3 mb-4 pr-2 pl-0&quot;]/div[@class=&quot;m-dropdown&quot;]/div[@class=&quot;dropdown&quot;]/a[@id=&quot;sortby&quot;]</value>
      <webElementGuid>7ee5440a-74fb-4c5a-b525-7e1fd5f6543c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//a[@id='sortby'])[2]</value>
      <webElementGuid>70f94475-6bcf-43e2-8caa-4891e94ec076</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/div/div[4]/main/div/div/div/div/div/div/a</value>
      <webElementGuid>0208d455-7611-418f-92ff-cde6160fb74e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Ordenar por:')])[2]</value>
      <webElementGuid>4788802a-1d22-4ca1-a6e5-066582d4c732</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Suburbia (1)'])[1]/following::a[1]</value>
      <webElementGuid>457e725a-7ee0-4ed7-a3f7-ce3816d6f9bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pottery Barn (1)'])[1]/following::a[1]</value>
      <webElementGuid>0ec5b82d-a25a-48be-b83b-f6b43b94a9d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Relevancia'])[2]/preceding::a[1]</value>
      <webElementGuid>ae2dcb79-9eba-4751-80f3-d0ef039be20c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lo Más Nuevo'])[2]/preceding::a[1]</value>
      <webElementGuid>e4d512ae-9ce7-4f5f-8749-c8d19005dbb8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/tienda?s=vaso#!')])[6]</value>
      <webElementGuid>5ec7a65a-fc16-47e2-b7b5-13f7a236ce84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//main/div/div/div/div/div/div/a</value>
      <webElementGuid>98f9cd00-8b4e-49c9-8515-49293856add7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'sortby' and @href = '/tienda?s=vaso#!' and (text() = 'Ordenar por:' or . = 'Ordenar por:')]</value>
      <webElementGuid>71711179-f355-4d9f-9c90-f5ab1a842939</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
