<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Relevancia</name>
   <tag></tag>
   <elementGuidId>df08b1a0-6362-4cba-85af-39eee3aff4f4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.col-lg-4.col-xl-3.mb-4.pr-2.pl-0 > div.m-dropdown > div.dropdown > div.dropdown-menu.show > button.dropdown-item</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[8]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>fd48f6ee-0d89-4838-8a3a-3311037028fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-item</value>
      <webElementGuid>bf4b794a-8bee-461a-ad08-d7e5064bfad2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>fc3f6dce-e90b-4bb4-bca2-4e565e3a8ab6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>datahref</name>
      <type>Main</type>
      <value>/tienda/Relevancia|0</value>
      <webElementGuid>eb7da749-9ff7-4b4d-8a61-b61c9e9c9d91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Relevancia</value>
      <webElementGuid>0f24c33e-d544-43cc-8b4c-fc6724ab223c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;min-vh-100&quot;]/div[@class=&quot;container-fluid o-main-container p-0 o-plp-secondaryContainer&quot;]/div[@class=&quot;container o-container__secondary search---&quot;]/div[@class=&quot;row mt-lg-3 m-row-bootstrap&quot;]/main[@class=&quot;col-lg-9 m-column_mainContent&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-12 d-none d-lg-block pr-1 pr-1 pl-lg-1 pr-lg-1&quot;]/div[@class=&quot;d-flex align-items-center&quot;]/div[@class=&quot;col-lg-4 col-xl-3 mb-4 pr-2 pl-0&quot;]/div[@class=&quot;m-dropdown&quot;]/div[@class=&quot;dropdown&quot;]/div[@class=&quot;dropdown-menu show&quot;]/button[@class=&quot;dropdown-item&quot;]</value>
      <webElementGuid>bbf4049d-5126-4233-9803-2dbd468b9545</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[8]</value>
      <webElementGuid>a81825b3-a00a-4abf-b2cb-7005597dd3f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/div/div[4]/main/div/div/div/div/div/div/div/button</value>
      <webElementGuid>25800a90-4032-4ded-b82b-141764bfe850</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ordenar por:'])[2]/following::button[1]</value>
      <webElementGuid>1799d813-3842-4f43-9434-9e08606d733d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Suburbia (1)'])[1]/following::button[1]</value>
      <webElementGuid>8cfd9189-a7f3-4d57-9f73-1ac672e5ab3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lo Más Nuevo'])[2]/preceding::button[1]</value>
      <webElementGuid>15bf8ff6-948a-4f2d-b1f8-b462f19a2160</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Menor precio'])[2]/preceding::button[2]</value>
      <webElementGuid>7a912a9c-a1ac-4163-ba7c-fde6466d30df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//main/div/div/div/div/div/div/div/button</value>
      <webElementGuid>011020c0-c4e8-4477-b7f8-c3b6bd69458b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Relevancia' or . = 'Relevancia')]</value>
      <webElementGuid>9a936256-2bf2-4a00-8410-82c7b2fa367a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
