<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Ms vendido_img_0_srp</name>
   <tag></tag>
   <elementGuidId>dd0c2977-01fc-4950-b1cc-14f3935adb19</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='img_0']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#img_0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>47324ad3-7cca-41ae-94ea-cabf699c1475</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>3b7dabec-0e9f-4921-bc2e-cb2798395155</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://media20qa.liverpool.com.mx/web/images/products/es_MX/sm/19480593.jpg</value>
      <webElementGuid>5b9042b3-4667-4c4a-a9ef-e0bdfdaf6993</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Asas para Vaso Antigoteo Avent Philips</value>
      <webElementGuid>e16a62ab-cd42-4e11-8412-fe1af2ddb2c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>img_0</value>
      <webElementGuid>fe550844-0816-4a1a-9ff4-cc7f32332640</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;img_0&quot;)</value>
      <webElementGuid>3895eb10-435b-4004-bde8-a6543a311d45</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='img_0']</value>
      <webElementGuid>6baee44b-d499-4413-9cf8-7a745695c725</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/div/div[4]/main/div[2]/div/div/ul/li/a/div/figure/div/section/img</value>
      <webElementGuid>d696a6dc-fbf9-49dc-834d-295ad08e63cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Asas para Vaso Antigoteo Avent Philips']</value>
      <webElementGuid>77b73270-822f-45ab-98a0-18e2da8f9ad1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/img</value>
      <webElementGuid>bf4d8226-b019-4c27-9e29-a520805600b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://media20qa.liverpool.com.mx/web/images/products/es_MX/sm/19480593.jpg' and @alt = 'Asas para Vaso Antigoteo Avent Philips' and @id = 'img_0']</value>
      <webElementGuid>b97a02b1-304d-4f0c-b3d1-1aabe389ee2a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
