<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Actualizar Datos Personales</name>
   <tag></tag>
   <elementGuidId>6aaf0cb7-57b9-44f1-b9aa-39cf7f387646</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div[2]/div/div[4]/aside/div/div[4]/div/div/ul/li/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>941a69e7-8839-4ae9-8737-7cee32e2fc93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/tienda/users/myAccount#!</value>
      <webElementGuid>970f8d21-857c-42f0-9e15-29a706876cbd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Actualizar Datos Personales</value>
      <webElementGuid>1b7c1262-a2da-484c-9bf0-5527dc2f320f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;container-fluid o-main-container p-0&quot;]/div[@class=&quot;container o-container__secondary&quot;]/div[@class=&quot;row mt-lg-3 m-row-bootstrap&quot;]/aside[@class=&quot;col-lg-3 pr-4 m-aside__content&quot;]/div[@class=&quot;o-myAccount-aside o-myAccount-aside&quot;]/div[@class=&quot;m-card-list--aside&quot;]/div[@class=&quot;m-card-title--aside&quot;]/div[@class=&quot;m-card-body--aside&quot;]/ul[@class=&quot;m-cardBody__margin&quot;]/li[@class=&quot;a-category__title&quot;]/a[1]</value>
      <webElementGuid>a955b9df-7320-4083-b1b9-7c8a0dc87a41</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div[2]/div/div[4]/aside/div/div[4]/div/div/ul/li/a</value>
      <webElementGuid>8583ef2d-9b9f-42a8-b30e-b7968bc0fa6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Actualizar Datos Personales')]</value>
      <webElementGuid>e0a4dda3-8b44-44ba-8c75-0650b921c2de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Datos de mi cuenta'])[1]/following::a[1]</value>
      <webElementGuid>9cf31a54-269f-4400-a297-4c47c06e2220</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mis formas de pago'])[1]/following::a[1]</value>
      <webElementGuid>aee224ad-dc96-4a79-87c0-7c39f7a57acb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Direcciones de Entrega'])[1]/preceding::a[1]</value>
      <webElementGuid>0e35d7ad-9e15-4ea1-afaf-92f4fa5e87a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Teléfonos Celulares'])[1]/preceding::a[2]</value>
      <webElementGuid>390666d3-a5e1-4dc2-8fbb-708ae3464336</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Actualizar Datos Personales']/parent::*</value>
      <webElementGuid>0e0007da-2111-460a-a715-cb6f8e9c7f19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/tienda/users/myAccount#!')])[8]</value>
      <webElementGuid>622400db-a696-42fc-8481-6cfef7e83142</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/ul/li/a</value>
      <webElementGuid>dc3afe4a-c9ee-4fce-96c6-3a1dcf38a040</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/tienda/users/myAccount#!' and (text() = 'Actualizar Datos Personales' or . = 'Actualizar Datos Personales')]</value>
      <webElementGuid>69bf3f77-47b8-4cb7-8524-d6382f3b5715</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
