<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Aviso de privacidad</name>
   <tag></tag>
   <elementGuidId>c735d1c4-3e8e-40cc-9dfb-b9bdb93e8e00</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/footer/div/div[2]/div[2]/a[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>1a4f9614-5c22-4db8-8407-256cf90cab8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-footer__disclaimers</value>
      <webElementGuid>4f035e88-aa15-4ab0-b143-5382e3789bda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>cb105765-dd6e-4cae-8029-84b50b303a90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://assetspwaqa.liverpool.com.mx/ayuda/index.html?_ga=2.157776568.341826744.1668396130-175376040.1668396130#/sec/terminos-y-condiciones/proteccion-de-datos/aviso-clientes</value>
      <webElementGuid>6f594e41-dff5-4e1d-b3e5-d6261049f824</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Aviso de privacidad</value>
      <webElementGuid>501741dc-30de-447b-a351-82be1749906d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/footer[1]/div[@class=&quot;container&quot;]/div[@class=&quot;row align-items-center&quot;]/div[@class=&quot;col-12 col-lg-4 text-center order-2 pb-4 pb-lg-0&quot;]/a[@class=&quot;a-footer__disclaimers&quot;]</value>
      <webElementGuid>a414a546-6992-4cb1-91d6-6ed273c365fb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/footer/div/div[2]/div[2]/a[2]</value>
      <webElementGuid>f7e65ee6-cc7c-483f-a573-bb882fd64542</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Aviso de privacidad')]</value>
      <webElementGuid>4cfd949c-46d6-4098-9e23-0238b45cc871</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='/'])[1]/following::a[1]</value>
      <webElementGuid>c5cff7ea-04cb-4dfc-8ce8-04224a8da7bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Términos y condiciones'])[1]/following::a[1]</value>
      <webElementGuid>c790a281-2de7-4991-850c-6412921762d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='/'])[2]/preceding::a[1]</value>
      <webElementGuid>64d3f7f7-1c36-4aad-a34a-675958270763</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mapa del Sitio'])[1]/preceding::a[1]</value>
      <webElementGuid>42ff0c78-318b-42a0-a701-a348184db89b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Aviso de privacidad']/parent::*</value>
      <webElementGuid>4de9faab-33be-44e6-b5ce-7efe726e110a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://assetspwaqa.liverpool.com.mx/ayuda/index.html?_ga=2.157776568.341826744.1668396130-175376040.1668396130#/sec/terminos-y-condiciones/proteccion-de-datos/aviso-clientes')]</value>
      <webElementGuid>9ef2538c-0ff7-42d7-94d7-af5ee1bb950f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/a[2]</value>
      <webElementGuid>2d27307c-02a0-444d-8a57-9ac9a26ff997</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://assetspwaqa.liverpool.com.mx/ayuda/index.html?_ga=2.157776568.341826744.1668396130-175376040.1668396130#/sec/terminos-y-condiciones/proteccion-de-datos/aviso-clientes' and (text() = 'Aviso de privacidad' or . = 'Aviso de privacidad')]</value>
      <webElementGuid>fc28ee7b-4165-4dcd-9e17-bbb271ec2e2a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
