<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Ayuda</name>
   <tag></tag>
   <elementGuidId>c54f642e-e782-4b0c-bc6e-ede857e29e08</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='#collapseSupport']/div/ul/li[2]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>c7503ca4-6a15-45bd-89ec-9e82471811bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-footer__link</value>
      <webElementGuid>6537c1ba-aa41-42f9-80d7-c0463cfeaa89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://assetspwaqa.liverpool.com.mx/ayuda/index.html?_ga=2.93150751.341826744.1668396130-175376040.1668396130#/</value>
      <webElementGuid>18342818-2fa0-4e54-8160-8126cd19ec75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Ayuda</value>
      <webElementGuid>4ad140ce-4aee-4e67-909d-45a8455d4262</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;#collapseSupport&quot;)/div[@class=&quot;card-body pt-0 pb-lg-0&quot;]/ul[@class=&quot;m-0&quot;]/li[@class=&quot;p-0&quot;]/a[@class=&quot;a-footer__link&quot;]</value>
      <webElementGuid>a23f7ff0-a2a8-4b0a-a59d-5f4a887ec751</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='#collapseSupport']/div/ul/li[2]/a</value>
      <webElementGuid>98c21843-f31e-4eff-9c95-40b6488809ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Ayuda')])[2]</value>
      <webElementGuid>803aeb6e-d724-46c7-be02-b5a26a30c6e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Facturación'])[1]/following::a[1]</value>
      <webElementGuid>da51ed1b-1500-4c25-9e8f-00025e8d0218</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Soporte al cliente'])[1]/following::a[2]</value>
      <webElementGuid>cfef8ed7-aba5-4044-90e0-f1be26b36f06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mis Compras'])[2]/preceding::a[1]</value>
      <webElementGuid>923a255a-7d80-4180-975d-244995b84481</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Garantía Liverpool'])[1]/preceding::a[2]</value>
      <webElementGuid>57f91531-4d17-4cdb-aa7a-938ad911be56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://assetspwaqa.liverpool.com.mx/ayuda/index.html?_ga=2.93150751.341826744.1668396130-175376040.1668396130#/')]</value>
      <webElementGuid>0c8d91c1-a7ed-48d7-a878-ada31bfcbf50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nav/div/div/div/div/div[2]/div/ul/li[2]/a</value>
      <webElementGuid>a771a798-1324-4999-9836-8b3f298e3b2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://assetspwaqa.liverpool.com.mx/ayuda/index.html?_ga=2.93150751.341826744.1668396130-175376040.1668396130#/' and (text() = 'Ayuda' or . = 'Ayuda')]</value>
      <webElementGuid>0aa4acbd-28b6-4b32-8194-d9f11b6c338b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
