<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Bolsa de trabajo</name>
   <tag></tag>
   <elementGuidId>2b0aad7e-e4c2-4794-8dae-d02fdf2a67ff</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='#collapseAboutUss']/div/ul/li/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>1603a08b-d76a-4401-8a92-fc9b63cd246d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-footer__link</value>
      <webElementGuid>e3d94400-a1f2-4d55-8697-057ad6c6ebe8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://tucarrera-elpuertode.liverpool.com.mx/vida-en-el-puerto?_ga=2.211649429.1824715639.1668414642-33942941.1668414642</value>
      <webElementGuid>66e61714-92a6-45e7-a5e4-ff35bfc96988</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Bolsa de trabajo</value>
      <webElementGuid>e3a95cb2-87d1-4b31-8f14-e7a62846bc7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;#collapseAboutUss&quot;)/div[@class=&quot;card-body pt-0 pb-lg-0&quot;]/ul[@class=&quot;m-0&quot;]/li[@class=&quot;p-0&quot;]/a[@class=&quot;a-footer__link&quot;]</value>
      <webElementGuid>fccf9bce-d6f9-46b6-b7d7-768d71383528</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='#collapseAboutUss']/div/ul/li/a</value>
      <webElementGuid>5f261694-6247-4f3b-87e9-a2979916a1ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Bolsa de trabajo')]</value>
      <webElementGuid>7394a935-5594-4ed7-aeeb-315087efdeb5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Acerca de Liverpool'])[1]/following::a[1]</value>
      <webElementGuid>50873bde-fc0d-447c-aacb-c31c66df7c9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ventas Corporativas'])[1]/following::a[1]</value>
      <webElementGuid>3261e546-4844-4045-a1da-82b3ebf6e2f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='¿Quiénes somos?'])[1]/preceding::a[1]</value>
      <webElementGuid>ad20a98d-d4ed-49c8-89a5-5b2109d8c6f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Relación con inversionistas'])[1]/preceding::a[2]</value>
      <webElementGuid>6755c32d-efa1-4595-b9cc-2fed8c9a86fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Bolsa de trabajo']/parent::*</value>
      <webElementGuid>0337c95f-e1b6-4314-85a2-42238115d215</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://tucarrera-elpuertode.liverpool.com.mx/vida-en-el-puerto?_ga=2.211649429.1824715639.1668414642-33942941.1668414642')]</value>
      <webElementGuid>893f452d-8037-4bbe-8cea-365288e5c14b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[2]/div/ul/li/a</value>
      <webElementGuid>14927d18-e89f-4116-8254-c0fb35d2b4ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://tucarrera-elpuertode.liverpool.com.mx/vida-en-el-puerto?_ga=2.211649429.1824715639.1668414642-33942941.1668414642' and (text() = 'Bolsa de trabajo' or . = 'Bolsa de trabajo')]</value>
      <webElementGuid>67395e99-cbac-4570-a806-4d614d1ee722</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
