<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Crdito_footer</name>
   <tag></tag>
   <elementGuidId>6ee77875-b440-4d01-8d51-b5623cfe816e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'Crédito')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>87685116-3bbc-4a09-b568-6fb630a5cf33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-footer__link</value>
      <webElementGuid>f1daae09-918b-4723-8a44-e6e9a2749b64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://micreditoqa.liverpool.com.mx:4042/app/?_ga=2.223871451.1544537127.1668335133-2095873409.1668335133</value>
      <webElementGuid>2ea6c754-5b1b-4d0c-aefc-4b8cddf5375c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Crédito</value>
      <webElementGuid>c72b83ef-bb3a-4c6c-9398-961fdfce9054</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;#collapseRefundAndCancel&quot;)/div[@class=&quot;card-body pt-0 pb-lg-0&quot;]/ul[@class=&quot;m-0&quot;]/li[@class=&quot;p-0&quot;]/a[@class=&quot;a-footer__link&quot;]</value>
      <webElementGuid>ab62ca3d-e2ae-48ef-a24f-212a8c44e743</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='#collapseRefundAndCancel']/div/ul/li/a</value>
      <webElementGuid>56762336-6f91-483e-8746-c7f656e8eb1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Crédito')]</value>
      <webElementGuid>e5d46bd3-5c2b-4483-9927-68f9b483cbe6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Servicios Liverpool'])[1]/following::a[1]</value>
      <webElementGuid>4ad447db-8ddd-49c0-9b27-1eda9fec6d3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Garantía Liverpool'])[1]/following::a[1]</value>
      <webElementGuid>1251d238-3015-4ab8-9a20-5c1f591d1875</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Concursos y promociones'])[1]/preceding::a[2]</value>
      <webElementGuid>ca98995a-82f7-4225-b80e-b9bbee4faec6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Diseño de Interiores'])[1]/preceding::a[3]</value>
      <webElementGuid>cbb4c2ca-871e-4313-a3fc-ee5692eca8ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Crédito']/parent::*</value>
      <webElementGuid>38997ad1-ae43-42e4-bff7-d866b598216a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://micreditoqa.liverpool.com.mx:4042/app/?_ga=2.223871451.1544537127.1668335133-2095873409.1668335133')]</value>
      <webElementGuid>ca62236f-1000-453a-af7e-5cf581a84aff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nav/div/div/div[2]/div/div[2]/div/ul/li/a</value>
      <webElementGuid>de41d15a-a2fa-47f0-905e-07b755bb17e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://micreditoqa.liverpool.com.mx:4042/app/?_ga=2.223871451.1544537127.1668335133-2095873409.1668335133' and (text() = 'Crédito' or . = 'Crédito')]</value>
      <webElementGuid>ac052516-7b02-4a08-a732-f1a6ba07d04b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
