<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Promociones_breadCrumb</name>
   <tag></tag>
   <elementGuidId>f95a1751-d14f-48cc-9447-61df3277fc6e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='abc']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#abc</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>dfd75569-922e-4d45-a571-d60dd9159541</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-breadcrumb__label</value>
      <webElementGuid>f078aa21-b0e1-40aa-a505-1fc034b09d7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>abc</value>
      <webElementGuid>76434813-8b2c-43ae-aeb0-83a0c9e9b885</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/tienda/promotions#!</value>
      <webElementGuid>162e6755-c376-4a3b-9253-d2ad8752d82c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Promociones</value>
      <webElementGuid>2a1f8ed8-5432-4b61-847c-b8142d435282</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;abc&quot;)</value>
      <webElementGuid>4d362036-2f0d-4312-a88f-275d09ae03aa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='abc']</value>
      <webElementGuid>30bbb7aa-f616-41da-b1c3-01f7badb3946</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/section/div/div/div/div/div/div/ul/li[2]/a</value>
      <webElementGuid>0cabceb4-409d-440a-a642-6f27a7b0b04e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Promociones')])[2]</value>
      <webElementGuid>08809f1d-9225-47ed-bd3d-64b0e956d0d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Home'])[1]/following::a[1]</value>
      <webElementGuid>3243b77c-eeb8-45cb-aa13-8cdcee280518</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Citas en tienda'])[1]/following::a[2]</value>
      <webElementGuid>98d6f0c8-31f6-48dc-b8f4-ba342df7605c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Conoce todas nuestras promociones'])[1]/preceding::a[1]</value>
      <webElementGuid>27128184-dfca-4315-b36b-55814f96aaf6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Todas'])[1]/preceding::a[1]</value>
      <webElementGuid>233c4282-c604-4bb3-a43e-f9599ef46d76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/tienda/promotions#!')])[185]</value>
      <webElementGuid>2940ff89-a196-4615-b5d5-75f9ebd606f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/div/div/div/div/div/div/ul/li[2]/a</value>
      <webElementGuid>c79635ee-deba-44b1-99a8-e354d405945e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'abc' and @href = '/tienda/promotions#!' and (text() = 'Promociones' or . = 'Promociones')]</value>
      <webElementGuid>d0bc8772-245c-44cf-b74c-f67efa111d5b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
