<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Suscrbete a nuestro Newsletter_hp</name>
   <tag></tag>
   <elementGuidId>c6ed9949-d899-4fdc-8718-0920e53c282a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/footer/div/div/div[3]/div/div/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.a-footer__boletin</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>9a0d491d-f1b4-45a5-8cdc-ecf0b0224e6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-footer__boletin</value>
      <webElementGuid>99bc0aa7-709f-4b94-a799-30a7a17f32be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://pwaqa.liverpool.com.mx/tienda/paginas/Boletin/boletin?_ga=2.162036414.341826744.1668396130-175376040.1668396130</value>
      <webElementGuid>4d92f1df-df0a-4e58-93bd-86614e6e042e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Suscríbete a nuestro Newsletter</value>
      <webElementGuid>9a96ce3a-8417-4455-b115-fb44a1681167</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/footer[1]/div[@class=&quot;container&quot;]/div[@class=&quot;row align-items-top&quot;]/div[@class=&quot;col-12 col-lg-4 d-footer--padding&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-12 pt-3 pt-lg-0 order-1&quot;]/a[@class=&quot;a-footer__boletin&quot;]</value>
      <webElementGuid>23ad8fe5-da04-460e-9499-4dda94f8eb19</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/footer/div/div/div[3]/div/div/a</value>
      <webElementGuid>59c86bd9-5dd3-47eb-b25f-6777e80d38da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Suscríbete a nuestro Newsletter')]</value>
      <webElementGuid>7f07317f-f9cf-4738-837b-60c1ea31e63f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Venta Nocturna'])[1]/following::a[1]</value>
      <webElementGuid>9d0855e3-9cb0-435b-bbf9-89db89166864</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sostenibilidad'])[1]/following::a[2]</value>
      <webElementGuid>e5d8c8ab-8a79-43e3-93ae-c68006840ea6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='WhatsApp'])[1]/preceding::a[1]</value>
      <webElementGuid>75bff787-5cf7-4853-af2a-16a58f7592a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Comentarios y Sugerencias:'])[1]/preceding::a[2]</value>
      <webElementGuid>28f701d8-c0dd-4345-80d7-56ae380ba345</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Suscríbete a nuestro Newsletter']/parent::*</value>
      <webElementGuid>eaaa6b54-2ba3-4a24-b42f-c74ea8e38a01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://pwaqa.liverpool.com.mx/tienda/paginas/Boletin/boletin?_ga=2.162036414.341826744.1668396130-175376040.1668396130')]</value>
      <webElementGuid>ce4b8cac-ac8a-48a7-82fd-7fc5e8b8a111</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//footer/div/div/div[3]/div/div/a</value>
      <webElementGuid>a8710dac-087c-428a-ab71-3231e3c7cca1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://pwaqa.liverpool.com.mx/tienda/paginas/Boletin/boletin?_ga=2.162036414.341826744.1668396130-175376040.1668396130' and (text() = 'Suscríbete a nuestro Newsletter' or . = 'Suscríbete a nuestro Newsletter')]</value>
      <webElementGuid>cbb70c94-8e71-48c5-b5e3-2d55d897afef</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
