<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Trminos y condiciones_hp</name>
   <tag></tag>
   <elementGuidId>f87d10ae-2da0-499e-b939-a64978694cb6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/footer/div/div[2]/div[2]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.a-footer__disclaimers</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>b1a94f26-237d-4bbd-bef4-0d6e4f494d6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-footer__disclaimers</value>
      <webElementGuid>77a505a2-31a0-4068-b4e6-5cacf19d3369</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>0567adf8-f7cf-4bd0-9d8f-76ee2bc01923</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://assetspwaqa.liverpool.com.mx/ayuda/index.html?_ga=2.160317375.341826744.1668396130-175376040.1668396130#/sec/terminos-y-condiciones/informacion</value>
      <webElementGuid>b681ab4c-a6fe-411b-a383-00ac58a55b03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Términos y condiciones</value>
      <webElementGuid>0c319660-81b3-4f3b-bd21-f533bdea740e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/footer[1]/div[@class=&quot;container&quot;]/div[@class=&quot;row align-items-center&quot;]/div[@class=&quot;col-12 col-lg-4 text-center order-2 pb-4 pb-lg-0&quot;]/a[@class=&quot;a-footer__disclaimers&quot;]</value>
      <webElementGuid>68bb9b21-aeb1-4390-bbc6-4e66e36e5aee</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/footer/div/div[2]/div[2]/a</value>
      <webElementGuid>abf63412-e206-49a0-bc15-047935240633</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Términos y condiciones')]</value>
      <webElementGuid>afde4c94-15d9-41fc-99b3-2bccb26b017c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='atencion@liverpool.com.mx'])[1]/following::a[1]</value>
      <webElementGuid>cb386fde-f309-4219-9896-31e0523ea92c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Comentarios y Sugerencias:'])[1]/following::a[1]</value>
      <webElementGuid>75be684b-9b32-447b-8211-9d4d4ba9149a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='/'])[1]/preceding::a[1]</value>
      <webElementGuid>18a05a83-5058-455d-aef7-82c572f4bf53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Aviso de privacidad'])[1]/preceding::a[1]</value>
      <webElementGuid>e8099876-b50c-4090-bd07-71d6246cc0bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Términos y condiciones']/parent::*</value>
      <webElementGuid>d291161a-ab09-4d36-84a5-0900b5d899ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://assetspwaqa.liverpool.com.mx/ayuda/index.html?_ga=2.160317375.341826744.1668396130-175376040.1668396130#/sec/terminos-y-condiciones/informacion')]</value>
      <webElementGuid>9b2944ea-bad6-4c34-a38c-bc50dadff503</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//footer/div/div[2]/div[2]/a</value>
      <webElementGuid>727f58c1-b496-444d-8e77-87c5fca32aac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://assetspwaqa.liverpool.com.mx/ayuda/index.html?_ga=2.160317375.341826744.1668396130-175376040.1668396130#/sec/terminos-y-condiciones/informacion' and (text() = 'Términos y condiciones' or . = 'Términos y condiciones')]</value>
      <webElementGuid>7527c4f5-3d2f-4b89-b1a4-4142b71dd414</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
