<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Map_slp</name>
   <tag></tag>
   <elementGuidId>9b9ede3d-88cc-40e4-b3a9-8f9d24d908e1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='7A29A427-637D-4427-96DE-DEDE4555DD52']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#7A29A427-637D-4427-96DE-DEDE4555DD52</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ece37671-ce9f-4f45-b5b0-ab9a9735d9db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>draggable</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>cfeacbe5-c72b-491a-ab78-adb7dcfa5c57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Show street map</value>
      <webElementGuid>9f913a2a-690f-400c-8c1a-a2fc9e1ac29f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Show street map</value>
      <webElementGuid>6023b5ad-5de1-48e4-8bfb-90b89d6da1f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>047ed0fb-22c5-4895-b1c2-7eb6d4f07d8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>menuitemradio</value>
      <webElementGuid>5aa41a12-d624-4449-9cbd-8742d3650812</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-checked</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>7fabfe35-a022-4939-927b-eba9403d3ac7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>10424cae-71e6-4776-b66d-f312aad3819b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>7A29A427-637D-4427-96DE-DEDE4555DD52</value>
      <webElementGuid>c3e911c8-5cd5-4d99-8644-1f388b267375</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Map</value>
      <webElementGuid>a2287d43-56b3-4d9a-b42a-fdd615e1f4b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;7A29A427-637D-4427-96DE-DEDE4555DD52&quot;)</value>
      <webElementGuid>cc89d0b5-db26-48f0-af61-d9919fb5dd9c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='7A29A427-637D-4427-96DE-DEDE4555DD52']</value>
      <webElementGuid>e23c78b8-3a9a-482c-8416-eaab71163dbb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/div[2]/div/div/div/div/div/div/div[4]/div/div/button</value>
      <webElementGuid>26cc131a-d8d9-4344-a4dc-c1d0bdea06dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='To navigate, press the arrow keys.'])[1]/following::button[1]</value>
      <webElementGuid>4f1ccd2d-4fc3-473f-8b63-0924fbae31ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Filtrar'])[1]/following::button[2]</value>
      <webElementGuid>426084e9-a414-4ea2-ad4b-45bb9a9e355d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Terrain'])[1]/preceding::button[1]</value>
      <webElementGuid>6b24b778-8793-4a95-8962-9b0378c82200</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Satellite'])[1]/preceding::button[1]</value>
      <webElementGuid>c30eb5eb-17e4-4cb5-9c82-97836453d1d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Map']/parent::*</value>
      <webElementGuid>5d925305-781b-40ca-9ddf-c41ffa2bf97c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/button</value>
      <webElementGuid>2520e24d-17c9-4357-ac00-f891c93bf62b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@title = 'Show street map' and @type = 'button' and @id = '7A29A427-637D-4427-96DE-DEDE4555DD52' and (text() = 'Map' or . = 'Map')]</value>
      <webElementGuid>0066eaed-fddf-4654-bfee-a9e1d59ede05</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
