<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>carousel1ProductName_hp</name>
   <tag></tag>
   <elementGuidId>5547dd3f-aead-4de8-a0dd-e9e85fa93883</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>p.a-card-description.description-size</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='trackCarousel']/div/div/div/a/figure/figcaption/p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>747f8d42-c6fe-4907-8727-46683eb82807</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-card-description description-size</value>
      <webElementGuid>c25cc514-44ad-450c-81b9-588714e15759</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Vaso-con-Boquilla-para-Nino-Evenflo</value>
      <webElementGuid>3d729a2e-72a8-4a32-9068-21207a871612</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;trackCarousel&quot;)/div[@class=&quot;slick-slide slick-cloned&quot;]/div[1]/div[@class=&quot;item&quot;]/a[1]/figure[@class=&quot;card m-card ma-figure&quot;]/figcaption[@class=&quot;card-body d-flex flex-column align-items-start pa-carousel&quot;]/p[@class=&quot;a-card-description description-size&quot;]</value>
      <webElementGuid>06e89df1-8b19-427e-99f2-6e3872f01e4b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='trackCarousel']/div/div/div/a/figure/figcaption/p</value>
      <webElementGuid>05e98287-54e3-4d91-b1bc-73b81ba7105b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Recomendaciones para ti'])[1]/following::p[1]</value>
      <webElementGuid>b05e3e90-02f8-4f16-bc1c-fb3aa286d0e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='%'])[1]/following::p[6]</value>
      <webElementGuid>e3987f42-fac1-405d-b0ab-d974f670ef4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mueblespara bebés'])[1]/preceding::p[12]</value>
      <webElementGuid>d7a57c93-8e26-481b-8909-e133266fc7d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='%'])[2]/preceding::p[13]</value>
      <webElementGuid>d96372d0-e534-443a-b54f-560aeec2a5b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Vaso-con-Boquilla-para-Nino-Evenflo']/parent::*</value>
      <webElementGuid>833efc27-1bc3-45ab-ae4f-4cd69f41c9e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//figcaption/p</value>
      <webElementGuid>da69af12-ad9a-43d8-8dfa-1f4739ac2ffb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Vaso-con-Boquilla-para-Nino-Evenflo' or . = 'Vaso-con-Boquilla-para-Nino-Evenflo')]</value>
      <webElementGuid>c36f0107-012a-4f41-b73a-cc353d1f5954</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
