<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>categoryNameInDepatmentos_hp</name>
   <tag></tag>
   <elementGuidId>51ace5ff-9c30-49d1-90ec-883e169c2c6e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@class='a-dekstop__categoryLink']//span[contains(text(),'​${categoryNameInTypeahead}')]
​</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
