<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>catridgeAImage_hp</name>
   <tag></tag>
   <elementGuidId>331467e2-7325-489f-ae7e-ecb9c823f17c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='carouselNo-1']/div[2]/div[2]/div/div[10]/div/div/a/figure/section/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>8013d115-c9cf-4ac6-bb3f-9e86762b2042</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>card-img-top lazyloaded</value>
      <webElementGuid>b26600f2-00bb-42aa-8c5e-5ec9bb7e6562</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-src</name>
      <type>Main</type>
      <value>https://media14qa.liverpool.com.mx/web/images/products/es_MX/xl/1026706615.jpg</value>
      <webElementGuid>7289f18e-ede0-4883-8c66-5c8f56ef0bad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Cartera para Dama Guess</value>
      <webElementGuid>8ac79941-074b-409d-aa40-a526e936f292</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://media14qa.liverpool.com.mx/web/images/products/es_MX/xl/1026706615.jpg</value>
      <webElementGuid>42776bfa-b399-4e4c-9139-c1243aa7fd4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;carouselNo-1&quot;)/div[@class=&quot;slick-slider slick-initialized&quot;]/div[@class=&quot;slick-list&quot;]/div[@class=&quot;slick-track&quot;]/div[@class=&quot;slick-slide&quot;]/div[1]/div[@class=&quot;item&quot;]/a[1]/figure[@class=&quot;card m-card ma-figure&quot;]/section[@class=&quot;still-image&quot;]/img[@class=&quot;card-img-top lazyloaded&quot;]</value>
      <webElementGuid>ec56e877-d522-48bf-85f2-d5d7b190c3a8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='carouselNo-1']/div[2]/div[2]/div/div[10]/div/div/a/figure/section/img</value>
      <webElementGuid>6dcee0ac-d1c6-43bc-b22f-c36974b98d42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Cartera para Dama Guess']</value>
      <webElementGuid>abac65c3-df4f-4bb1-81d3-d8717ab0de30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div/div/a/figure/section/img</value>
      <webElementGuid>f32a7bc1-fdb3-40e4-8dd2-1fc5fdda8899</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'Cartera para Dama Guess' and @src = 'https://media14qa.liverpool.com.mx/web/images/products/es_MX/xl/1026706615.jpg']</value>
      <webElementGuid>62a035b5-7f06-4f2a-b37f-ac3de9ee8636</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
