<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_RopaVer todo  Ver Todo Chamarras Abrigo_2924d2</name>
   <tag></tag>
   <elementGuidId>c0e03f7c-ded2-4276-a8e6-908c70254a0c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/main/div/div/div/div[2]/div/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.o-clp-mainContent</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>0c22c5aa-a546-4297-8400-4ed5957e02f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>o-clp-mainContent</value>
      <webElementGuid>2c649dc7-2057-4451-8e7c-3567971d005e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>RopaVer todo  Ver Todo Chamarras Abrigos &amp; Chalecos Suéteres &amp; Sudaderas Blusas Tallas Especiales Playeras Jeans Pantalones Vestidos &amp; Faldas Vestidos de Noche Lencería Trajes de baño Tendencias Suburbia</value>
      <webElementGuid>02b70f20-4d72-4cee-b781-d4690e834fdc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;min-vh-100&quot;]/main[1]/div[@class=&quot;container-fluid o-main-container p-0 o-clp-secondaryContainer&quot;]/div[@class=&quot;container o-container__secondary&quot;]/div[1]/div[@class=&quot;row mt-lg-3 m-row-bootstrap leftMenu-clpMobile&quot;]/div[@class=&quot;col-lg-9 m-column_mainContent clp_headband&quot;]/div[@class=&quot;o-clp-mainContent&quot;]</value>
      <webElementGuid>0b398986-f7ec-47ae-83fe-a32a0d6fd3be</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/main/div/div/div/div[2]/div/div[2]</value>
      <webElementGuid>d4441a91-779a-4289-8500-f4ca0e54d6cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Suburbia'])[1]/following::div[3]</value>
      <webElementGuid>dc255b70-6a8f-4d56-9ec2-78f063487696</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tendencias'])[2]/following::div[3]</value>
      <webElementGuid>e99d5b40-5af8-43f9-b983-9134b2193f8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//main/div/div/div/div[2]/div/div[2]</value>
      <webElementGuid>a18d6460-3c15-4255-83af-b001af461b6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'RopaVer todo  Ver Todo Chamarras Abrigos &amp; Chalecos Suéteres &amp; Sudaderas Blusas Tallas Especiales Playeras Jeans Pantalones Vestidos &amp; Faldas Vestidos de Noche Lencería Trajes de baño Tendencias Suburbia' or . = 'RopaVer todo  Ver Todo Chamarras Abrigos &amp; Chalecos Suéteres &amp; Sudaderas Blusas Tallas Especiales Playeras Jeans Pantalones Vestidos &amp; Faldas Vestidos de Noche Lencería Trajes de baño Tendencias Suburbia')]</value>
      <webElementGuid>6407336d-0c59-4d09-8894-0bd381436819</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
