<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Te escuchamos__headBandContainer</name>
   <tag></tag>
   <elementGuidId>8ee6fa60-cbc2-408e-b28a-fc0d5fea2214</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='_headBandContainer']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#_headBandContainer</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>a8437bff-8521-4cc1-9aae-150f5afb3bf0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_headBandContainer</value>
      <webElementGuid>2dc2c66a-dac1-432d-8b55-9787d3469f61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>_headBandContainer</value>
      <webElementGuid>c22c9350-1b41-4f2e-8d56-6923f231d4c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;_headBandContainer&quot;)</value>
      <webElementGuid>27d52189-27c4-4c5c-8db9-9ecb61469a64</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='_headBandContainer']</value>
      <webElementGuid>3c26749a-fe2c-4c93-b475-f0e3a16c22d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='bannerNo-1']/div</value>
      <webElementGuid>bb1e75c4-22c9-4720-a45a-39818e005c7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Te escuchamos'])[1]/following::div[6]</value>
      <webElementGuid>ee4c44bf-74ba-4806-9457-42f5821edc08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Selecciona tu tienda'])[2]/following::div[14]</value>
      <webElementGuid>736e47ca-e0ea-4990-b372-0fd16f7176c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Muebles'])[6]/preceding::div[2]</value>
      <webElementGuid>b8643a93-7f74-4f9d-ba95-ef40716a7280</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='%'])[1]/preceding::div[2]</value>
      <webElementGuid>f5e52e8e-bca1-4e11-a13d-ede6cc0baf63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//main/div/div/div/div</value>
      <webElementGuid>faaf385f-81d2-4fac-8cdf-93cd385bf77a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = '_headBandContainer']</value>
      <webElementGuid>a8c03dc6-9f4c-4ca7-9354-432f7f3e0529</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
