<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>facebook_footer</name>
   <tag></tag>
   <elementGuidId>1b972031-9542-4099-bfed-f944619c6f97</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/footer/div/div[2]/div[3]/a[2]/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.icon-facebook</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>121f5e26-c8dc-44c0-8157-1e4766559374</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon-facebook</value>
      <webElementGuid>bc3ddbfb-b396-4c59-8e17-759816757817</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/footer[1]/div[@class=&quot;container&quot;]/div[@class=&quot;row align-items-center&quot;]/div[@class=&quot;col-12 col-lg-4 text-lg-right text-center order-3 pb-4 pb-lg-0&quot;]/a[@class=&quot;a-footer__socialMedia&quot;]/i[@class=&quot;icon-facebook&quot;]</value>
      <webElementGuid>27aca691-633a-4a6e-82d4-2971961c8d84</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/footer/div/div[2]/div[3]/a[2]/i</value>
      <webElementGuid>e37ce3fa-f510-4f8c-a9bb-7bdcbc3e5ea9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]/i</value>
      <webElementGuid>a275f4a6-1469-42ae-a041-43fbb0e8e6df</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
