<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>grImage_grPage</name>
   <tag></tag>
   <elementGuidId>c5cce9fc-7116-49db-b71a-0f223f468f36</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//div[@id='mainBanner']/div/div/img)[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.headerLogo > img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>4b8d2c35-db77-4053-9a62-c356c39e079a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://assetspwa.liverpool.com.mx/assets/digital/mesas/img/web/header_mdr_logo.png</value>
      <webElementGuid>aca3a39c-e1ad-46f9-b54e-856167838e25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content&quot;)/div[@class=&quot;container-fluid&quot;]/div[@id=&quot;mainBanner&quot;]/div[@id=&quot;mainBanner&quot;]/div[@class=&quot;col-md-12 header&quot;]/div[@class=&quot;headerLogo&quot;]/img[1]</value>
      <webElementGuid>7c041bbf-7a8e-41c7-88d5-7190885e75a0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='mainBanner']/div/div/img)[2]</value>
      <webElementGuid>167cb740-cf65-48d2-81a7-c761f0cfb121</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://assetspwa.liverpool.com.mx/assets/digital/mesas/img/web/header_mdr_logo.png')]</value>
      <webElementGuid>4bfc5d5a-7d4e-4d81-8ad0-ec0ce4a77961</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/img</value>
      <webElementGuid>88361cfb-9f7a-4b72-9720-5645b65ce5e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://assetspwa.liverpool.com.mx/assets/digital/mesas/img/web/header_mdr_logo.png']</value>
      <webElementGuid>883e88b5-27b1-46c4-ac93-c6b64c92bb90</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
