<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h3_Trminos y condiciones_tnc</name>
   <tag></tag>
   <elementGuidId>40222b43-ef0b-4459-9a40-ed1ab0350862</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mainContent']/div/div/div/div/div/h3</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>h3.ng-binding</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h3</value>
      <webElementGuid>2768cf4a-8ff7-4b4a-ab5e-62f2746081ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-bind</name>
      <type>Main</type>
      <value>category.titulo</value>
      <webElementGuid>ebc17409-d0c1-4c95-97ef-4e19b069c528</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-binding</value>
      <webElementGuid>f37e620f-9982-412e-af6c-cbf62ce2ced8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Términos y condiciones</value>
      <webElementGuid>420c25d9-eb11-4218-85a0-5c161a6ff1d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mainContent&quot;)/div[@class=&quot;grid-container ng-scope&quot;]/div[@class=&quot;grid-100 head-category&quot;]/div[@class=&quot;grid-70 prefix-15 sufix-75&quot;]/div[@class=&quot;grid-40&quot;]/div[@class=&quot;tsunami&quot;]/h3[@class=&quot;ng-binding&quot;]</value>
      <webElementGuid>31ffba40-0a46-46bc-801a-2d727f38c711</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mainContent']/div/div/div/div/div/h3</value>
      <webElementGuid>bc6aba3e-20ba-4f2b-9633-20a2725230fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Términos y condiciones'])[2]/preceding::h3[1]</value>
      <webElementGuid>49c8641f-76b5-45f3-ad7d-354766441834</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Términos y Condiciones'])[1]/preceding::h3[1]</value>
      <webElementGuid>5f2a0210-09a5-406c-869f-951130c3919f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Términos y condiciones']/parent::*</value>
      <webElementGuid>678f4c62-b580-4b31-9feb-12df1ec4ff91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h3</value>
      <webElementGuid>df40dfe7-2b94-4c6d-85ef-6cbdeeb3a6c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h3[(text() = 'Términos y condiciones' or . = 'Términos y condiciones')]</value>
      <webElementGuid>de4962ea-058e-4d2f-aa33-6867de20b232</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
