<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Ms informacin_icon-close close_hp</name>
   <tag></tag>
   <elementGuidId>0429d253-530f-43d3-8fcc-41d7d7e14bca</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div[2]/div/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.icon-close.close</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>7e8ca56e-b70b-41d3-9873-c061c708fc51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon-close close</value>
      <webElementGuid>e21971fc-38ed-4af3-ba42-f00df9607d11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;cookiesMessage-wrapper&quot;]/div[@class=&quot;cookiesMessage-container&quot;]/i[@class=&quot;icon-close close&quot;]</value>
      <webElementGuid>e019687a-c8e3-4f68-91f4-015a9fe14e7b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div[2]/div/i</value>
      <webElementGuid>05264a64-bbf3-4bf8-bee5-c1ca651354c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/i</value>
      <webElementGuid>8bffcec7-7c87-4b33-b3c0-2ebb5e58c7c1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
