<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_elpuertode_jobPage</name>
   <tag></tag>
   <elementGuidId>5c30c1dd-5025-4d37-b226-c9d915f56d34</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//header[@id='atIdViewHeader']/div/div[2]/div/div/a/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.lzy1Td</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>d477a300-f755-465c-a3f5-f0e3db36a142</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://lh4.googleusercontent.com/8nkZJxY1ekuh3MZiA_WWrLnNmOKys82OTW82pTiHYK3xgrjolodBz7rvmVD-W6h-I_s9wzNmHrW8nxVzWL4QCGE=w16383</value>
      <webElementGuid>d7f9a7dc-e47b-4c21-9b09-bb1c207ab166</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lzy1Td</value>
      <webElementGuid>7141f7ef-8ad0-46fa-b222-ce8d56f39a5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>6efa5652-b9ec-4f10-8bb5-9b5064d5ad68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Site home</value>
      <webElementGuid>ea04496a-3fc1-41a5-b84d-613ac6950a8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>jsname</name>
      <type>Main</type>
      <value>SwcDWb</value>
      <webElementGuid>53ed044a-d54a-46a2-9776-238fc7ea3919</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;atIdViewHeader&quot;)/div[@class=&quot;BbxBP GBy4H K5Zlne&quot;]/div[@class=&quot;VLoccc K5Zlne QDWEj U8eYrb&quot;]/div[@class=&quot;Pvc6xe&quot;]/div[@class=&quot;TlfmSc YSH9J&quot;]/a[@class=&quot;GAuSPc&quot;]/img[@class=&quot;lzy1Td&quot;]</value>
      <webElementGuid>dfcd41b4-84ac-4d67-8e6c-0243b57fc22a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//header[@id='atIdViewHeader']/div/div[2]/div/div/a/img</value>
      <webElementGuid>b24a75f2-c682-4587-bb7c-896757952ef4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[contains(@src,'https://lh4.googleusercontent.com/8nkZJxY1ekuh3MZiA_WWrLnNmOKys82OTW82pTiHYK3xgrjolodBz7rvmVD-W6h-I_s9wzNmHrW8nxVzWL4QCGE=w16383')])[2]</value>
      <webElementGuid>26045bf6-3f6f-4331-90f6-4e8e990d1f0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/a/img</value>
      <webElementGuid>a2d02bb4-5efd-48f8-816a-f287b1e7a4e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://lh4.googleusercontent.com/8nkZJxY1ekuh3MZiA_WWrLnNmOKys82OTW82pTiHYK3xgrjolodBz7rvmVD-W6h-I_s9wzNmHrW8nxVzWL4QCGE=w16383']</value>
      <webElementGuid>d95b8990-f26e-4c18-9377-983ec5daecd3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
