<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_elpuertodeliverpool</name>
   <tag></tag>
   <elementGuidId>00d4ae20-be06-407d-aac6-505e2838a337</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@alt='logotipo de Liverpool']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;logotipo de Liverpool&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>3bc74e65-a09e-4dc1-9c2e-b6a05764e525</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>img/logo-el-puerto.png</value>
      <webElementGuid>f756a25d-f408-4008-9dbb-ccd21008809f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>logotipo de Liverpool</value>
      <webElementGuid>36e2af62-435b-4c27-ad54-0e469f523c16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/header[1]/div[@class=&quot;logo&quot;]/a[1]/img[1]</value>
      <webElementGuid>878bc276-504d-40da-9b21-7dbe4f728318</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='logotipo de Liverpool']</value>
      <webElementGuid>c3d5a16c-0038-48ae-8bcf-bdbec1979a2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>5d52760b-3789-4036-a119-4660921ed479</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'img/logo-el-puerto.png' and @alt = 'logotipo de Liverpool']</value>
      <webElementGuid>2b858f23-47c0-42b0-a5b1-b2cd0b54639b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
