<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_trabajo_jobPage</name>
   <tag></tag>
   <elementGuidId>1c3b1b77-65d2-422c-808c-8181fb1519d5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='h.3a644d2b3d777f86_46']/div/div/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>56ae1c43-b2e2-443d-8a73-cf0675113671</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://lh5.googleusercontent.com/BMnyUfbF9etsPkU2D9Ky0uZQ54-x6dwGCM7-ye5QyC9jQASc-14K8HAC7QgQzUmF211VgO9TvMl0hGouTv53wTUCLYS2EA_KjhRl3T-ZSj9EHnt0ZZjPeWqpMR_cQMLspQ=w1280</value>
      <webElementGuid>f3ea1aba-7153-4fba-aabf-3256b1afc573</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>CENy8b</value>
      <webElementGuid>a98877d9-fadf-45c9-aa48-47d1e71621a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>31ff5623-c08a-4445-8359-b210a3f39327</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;h.3a644d2b3d777f86_46&quot;)/div[@class=&quot;jXK9ad-SmKAyb&quot;]/div[@class=&quot;tyJCtd baZpAe&quot;]/div[@class=&quot;t3iYD&quot;]/img[@class=&quot;CENy8b&quot;]</value>
      <webElementGuid>a8a09fab-9d6d-4e35-a6a3-2b3775ac9fdd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='h.3a644d2b3d777f86_46']/div/div/div/img</value>
      <webElementGuid>f865eb16-4bc6-4069-a7bd-b16baa9ca0b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://lh5.googleusercontent.com/BMnyUfbF9etsPkU2D9Ky0uZQ54-x6dwGCM7-ye5QyC9jQASc-14K8HAC7QgQzUmF211VgO9TvMl0hGouTv53wTUCLYS2EA_KjhRl3T-ZSj9EHnt0ZZjPeWqpMR_cQMLspQ=w1280')]</value>
      <webElementGuid>dfa99ba5-25cb-44bc-9b59-030d53d9fc01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[5]/div[2]/div/div[2]/div/div/div[2]/div/div/div/div/img</value>
      <webElementGuid>d7dc5efc-6663-4233-a05b-93a2968fc4ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://lh5.googleusercontent.com/BMnyUfbF9etsPkU2D9Ky0uZQ54-x6dwGCM7-ye5QyC9jQASc-14K8HAC7QgQzUmF211VgO9TvMl0hGouTv53wTUCLYS2EA_KjhRl3T-ZSj9EHnt0ZZjPeWqpMR_cQMLspQ=w1280']</value>
      <webElementGuid>736f0aad-1adf-4a9b-bc62-8eeb725882f4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
