<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Apellido paterno_apellidoP_newsletter</name>
   <tag></tag>
   <elementGuidId>fed8c56b-378f-4dc3-bdad-604126125298</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='apellidoP']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#apellidoP</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b86f01fb-e2fd-4b47-9b41-1d424de9e6cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>apellidoP</value>
      <webElementGuid>6f60f678-a8f6-4003-91e6-8468d707bf94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>apellidoP</value>
      <webElementGuid>6e0f17ce-0ca2-4d9e-b1b1-3cac227e96b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_input</value>
      <webElementGuid>9b9a9ff1-68e9-4e25-a42d-ba9569a53594</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Ingresa tu apellido paterno</value>
      <webElementGuid>cfd6cbf9-d7c3-4256-907a-8cb12bfb1e7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ed53581a-6b02-4227-a66c-b6ac61e03a5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>a0f9abaa-815b-4b96-8519-ed18676c9097</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;apellidoP&quot;)</value>
      <webElementGuid>02f22223-5cc9-4ce8-a1ad-bab33bc759ef</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='apellidoP']</value>
      <webElementGuid>11de9675-e151-4d16-8c66-74c4f5c9a886</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='formFactory']/div[2]/input</value>
      <webElementGuid>8b03e803-6dc1-4bab-a635-d2bff78ee7e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>faad093c-8356-42f6-aef0-7dbfe6290065</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'apellidoP' and @id = 'apellidoP' and @placeholder = 'Ingresa tu apellido paterno' and @type = 'text']</value>
      <webElementGuid>7ecf63e7-5b61-47ce-8a23-f69781cc1405</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
