<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Apellido materno_apellidoM_newsletter</name>
   <tag></tag>
   <elementGuidId>6eaabdf5-6a46-42d3-aea0-ce52f7b847f4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='apellidoM']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#apellidoM</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>eaf8558b-c149-4046-b251-e04b507bc99d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>apellidoM</value>
      <webElementGuid>840e79d1-b29f-45e0-bacb-247e525dfdc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>apellidoM</value>
      <webElementGuid>088e7ae5-e325-48ee-a245-c302bf823b9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_input</value>
      <webElementGuid>75167a29-b491-4a62-b34f-bfe7e1c2a2ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Ingresa tu apellido materno</value>
      <webElementGuid>c6bc94b4-730e-4451-a848-b86b3667cf7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8776545c-4418-4468-badf-fd0c13482ad1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>6c9dbfb4-d3c6-4102-adbb-5b7a615f16c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;apellidoM&quot;)</value>
      <webElementGuid>5bae6fdf-9d37-48ad-9a93-3d07aeef92a4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='apellidoM']</value>
      <webElementGuid>0235e38f-74c5-4647-8080-a229a4d4694c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='formFactory']/div[3]/input</value>
      <webElementGuid>0a69c78b-cb1e-4e18-8368-7d71130eb7bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input</value>
      <webElementGuid>b29e20cc-4651-4a7b-8a30-412c335ef13d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'apellidoM' and @id = 'apellidoM' and @placeholder = 'Ingresa tu apellido materno' and @type = 'text']</value>
      <webElementGuid>cfeffd0a-298a-4f8c-ae47-9fb7cb23e5b1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
