<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>instagramLogo_instagramPage</name>
   <tag></tag>
   <elementGuidId>b347876c-e137-4901-89c9-b0f71542f901</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@class='_acup']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>svg.iconBullet</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>svg</value>
      <webElementGuid>b914f5bc-ef3b-424b-9465-0fd71f924225</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>iconBullet</value>
      <webElementGuid>8d0ff6be-ac16-431d-b8d1-257b050d4fbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>1ad4ef5e-e6a7-41e6-8cf4-4e7028869219</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>8de10999-0066-41dc-ba39-9a134de68a12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fill</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>d1eb7c6f-57d9-4e49-97cb-d028eb6835c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xmlns</name>
      <type>Main</type>
      <value>http://www.w3.org/2000/svg</value>
      <webElementGuid>a4752e0b-a8eb-4e2e-a303-cbdaa6c79d21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;min-vh-100&quot;]/div[1]/div[@class=&quot;container-fluid o-main-container p-0 o-blp-secondaryContainer&quot;]/div[@class=&quot;container o-container__secondary&quot;]/div[@class=&quot;row mt-lg-3 m-row-bootstrap&quot;]/aside[@class=&quot;col-lg-3 pr-lg-4 m-aside__content&quot;]/div[@class=&quot;col-12 mr-lg-4 order-2 order-lg-1 mb-3 px-0 o-column__aside&quot;]/div[1]/div[@class=&quot;m-leftMenu-wrapper plp-filter-options active&quot;]/div[@class=&quot;m-title-leftMenu-currentCategory&quot;]/svg[@class=&quot;iconBullet&quot;]</value>
      <webElementGuid>c8159146-c3cd-4cfa-b8ba-aa1b68d7266a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Home'])[1]/following::*[name()='svg'][1]</value>
      <webElementGuid>690108a4-13e6-4132-b211-4e15cc361634</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ella'])[3]/preceding::*[name()='svg'][1]</value>
      <webElementGuid>7405d149-a91b-44d1-b2cc-fdf251ae2c74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ropa'])[1]/preceding::*[name()='svg'][1]</value>
      <webElementGuid>14a4da3c-4e15-41d9-8030-a38f81051715</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
