<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>instagram_footer</name>
   <tag></tag>
   <elementGuidId>de8c4690-fb5b-4c82-86e2-3baf5f78d744</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/footer/div/div[2]/div[3]/a[4]/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.icon-instagram</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>d3b92655-e40a-43eb-a544-c9de584f23c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon-instagram</value>
      <webElementGuid>18fee1ba-b8fa-4942-95eb-9040638d745d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/footer[1]/div[@class=&quot;container&quot;]/div[@class=&quot;row align-items-center&quot;]/div[@class=&quot;col-12 col-lg-4 text-lg-right text-center order-3 pb-4 pb-lg-0&quot;]/a[@class=&quot;a-footer__socialMedia&quot;]/i[@class=&quot;icon-instagram&quot;]</value>
      <webElementGuid>22830d19-986c-43c1-8149-4c95254fb30b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/footer/div/div[2]/div[3]/a[4]/i</value>
      <webElementGuid>b5f19272-bfb9-4ec9-b79e-87e03ce294b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[4]/i</value>
      <webElementGuid>fd225b68-1d5e-4eb1-b67a-171d36d269dc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
