<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>recommendedSlotPriceProduct2_hp</name>
   <tag></tag>
   <elementGuidId>aaf8a4d0-5466-4942-bd0b-1a581b20f2c5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//div[@id='carouselNo-1']//p[@class='a-card-discount'])[2]​</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
