<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>recomendaciones-next-carousel</name>
   <tag></tag>
   <elementGuidId>e166c302-1766-411f-bb95-1b04e625f24f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#nextCarousel</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='nextCarousel']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>85118a1d-2ac5-4e5c-95be-3db4fd01f104</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nextCarousel</value>
      <webElementGuid>2a12df6b-daf3-41de-9fec-9c8443a2997c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>slick-arrow slick-next icon-arrow_right</value>
      <webElementGuid>c004e769-6052-4699-becc-7007259a1b4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nextCarousel&quot;)</value>
      <webElementGuid>1c841efa-c882-45e4-ac5c-278e76a7fc7c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='nextCarousel']</value>
      <webElementGuid>aa43e039-df8a-4767-9568-136a4532d031</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='carouselRecomendation']/div[2]/div[3]</value>
      <webElementGuid>12b62cac-915d-4858-b8fd-91ac1d1621cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[3]</value>
      <webElementGuid>5f913366-ae7c-495b-bc0e-e64425537b83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'nextCarousel']</value>
      <webElementGuid>2bcc8f2e-be02-4100-91ac-321c8b0e5811</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
