<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>recomendaciones-prev-carousel</name>
   <tag></tag>
   <elementGuidId>90db5a54-53e9-4c83-a0b9-faf144dd08a9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#prevCarousel</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='prevCarousel']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>6c8cd226-4b2b-4578-998f-55e6b656396a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>prevCarousel</value>
      <webElementGuid>ac46d606-56e5-44fe-bcfd-b7b82fd99f93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>slick-arrow slick-prev icon-arrow_left</value>
      <webElementGuid>dd861850-62db-4444-8bff-f2d8b743aab8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;prevCarousel&quot;)</value>
      <webElementGuid>1e1d02e0-6b6b-44ca-953a-be7d75641cba</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='prevCarousel']</value>
      <webElementGuid>3e596334-3107-46d2-b159-d6d2a1f583f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='carouselRecomendation']/div[2]/div</value>
      <webElementGuid>aace098b-5761-4703-a714-d1b97bc6edea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//main/div/div/div[2]/div/div[2]/div</value>
      <webElementGuid>8b755355-7c82-4af9-a725-2900dc18cf96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'prevCarousel']</value>
      <webElementGuid>b8f99963-378f-4932-ad85-7a5b936c23da</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
