<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>svg_Follow__ab6-</name>
   <tag></tag>
   <elementGuidId>56d51dd3-3aff-43e1-8966-a5844fb40e94</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Follow'])[81]/following::*[name()='svg'][32]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div._aagx > svg._ab6-</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>svg</value>
      <webElementGuid>e7acf862-ac1e-49fb-8861-f85f47d6e6b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Instagram</value>
      <webElementGuid>e51a1c7d-b210-42db-8209-7420ea2b193d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_ab6-</value>
      <webElementGuid>930e8bb7-617e-4191-bb8e-19b713fbaf54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>color</name>
      <type>Main</type>
      <value>#262626</value>
      <webElementGuid>b1f4e0e2-fd4c-46e4-a733-ea2e5fcb6109</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fill</name>
      <type>Main</type>
      <value>#262626</value>
      <webElementGuid>7a9cf865-377f-413c-a285-f2321b1eddb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>29</value>
      <webElementGuid>dcc6ca8e-c2a6-45a0-bb98-981d2f043806</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>50b2d6d9-bf6b-46ce-a22d-be75f65b9567</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>viewBox</name>
      <type>Main</type>
      <value>32 4 113 32</value>
      <webElementGuid>28ed7455-645f-459c-9b9f-cb9824a73009</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>103</value>
      <webElementGuid>fcd7af63-2a8c-48df-a7f8-2fe81a5dc725</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mount_0_0_za&quot;)/div[1]/div[1]/div[@class=&quot;x9f619 x1n2onr6 x1ja2u2z&quot;]/div[@class=&quot;x9f619 x1n2onr6 x1ja2u2z&quot;]/div[@class=&quot;x1ja2u2z x1n2onr6 xdt5ytf x78zum5&quot;]/div[@class=&quot;x78zum5 xdt5ytf x1n2onr6&quot;]/div[@class=&quot;x78zum5 xdt5ytf x1n2onr6 xat3117 xxzkxad&quot;]/div[@class=&quot;x78zum5 xdt5ytf x10cihs4 x1t2pt76 x1n2onr6 x1ja2u2z&quot;]/section[@class=&quot;_a997 _a998&quot;]/nav[@class=&quot;_acbh _acbi _acbk&quot;]/div[@class=&quot;_acc1 _acc3&quot;]/div[@class=&quot;_acum&quot;]/div[@class=&quot;_acun&quot;]/div[@class=&quot;_acup&quot;]/div[@class=&quot;_ab8w  _ab94 _ab99 _ab9f _ab9k _ab9p _abcm&quot;]/a[@class=&quot;x1i10hfl xjbqb8w x6umtig x1b1mbwd xaqea5y xav7gou x9f619 x1ypdohk xt0psk2 xe8uvvx xdj266r x11i5rnm xat24cr x1mh8g0r xexx8yu x4uap5 x18d9i69 xkhd6sd x16tdsg8 x1hl2dhg xggy1nq x1a2a7pz _a6hd&quot;]/div[@class=&quot;_ab8w  _ab94 _ab97 _ab9f _ab9k _ab9p _abcm&quot;]/div[@class=&quot;_aagx&quot;]/svg[@class=&quot;_ab6-&quot;]</value>
      <webElementGuid>31c6d640-1166-466a-8712-867c5f884ef9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Follow'])[81]/following::*[name()='svg'][32]</value>
      <webElementGuid>8e62c6c5-0120-400d-9e43-33a217c31c54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Muebles Dico'])[1]/following::*[name()='svg'][32]</value>
      <webElementGuid>15867e1e-940a-403a-80d5-ebd052cb200d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search'])[1]/preceding::*[name()='svg'][2]</value>
      <webElementGuid>fea838ff-1c8a-45c3-8ae3-03ecb2b354f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Log into Instagram'])[1]/preceding::*[name()='svg'][2]</value>
      <webElementGuid>7cd84f34-78c2-4018-9d1c-8ef4c8caf576</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
