<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>twitter_footer</name>
   <tag></tag>
   <elementGuidId>bcc3d6b7-ca6f-4bd0-b3c8-29f70083fe6b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/footer/div/div[2]/div[3]/a[3]/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.icon-twitter</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>227f31ca-3f3d-4ec7-b456-b35c28f3cdbf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon-twitter</value>
      <webElementGuid>6f167a0f-24e9-4ffb-b02e-9ab28a14f648</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/footer[1]/div[@class=&quot;container&quot;]/div[@class=&quot;row align-items-center&quot;]/div[@class=&quot;col-12 col-lg-4 text-lg-right text-center order-3 pb-4 pb-lg-0&quot;]/a[@class=&quot;a-footer__socialMedia&quot;]/i[@class=&quot;icon-twitter&quot;]</value>
      <webElementGuid>6624c08d-b815-4b97-ba5a-ea685fdbba55</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/footer/div/div[2]/div[3]/a[3]/i</value>
      <webElementGuid>e44121de-1ff4-4b4f-b001-ce0674ada42d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[3]/i</value>
      <webElementGuid>100613d9-0c7c-429d-b4f4-20add5b3aa50</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
