<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Ms informacin_icon-close close</name>
   <tag></tag>
   <elementGuidId>110b0250-87d7-494c-9233-83f20796d429</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div[2]/div/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.icon-close.close</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>4f00fbd8-f7d2-4b82-94f9-20206c81e006</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon-close close</value>
      <webElementGuid>bc825ec8-a8fb-46c2-b64a-d04210cbd8cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;cookiesMessage-wrapper&quot;]/div[@class=&quot;cookiesMessage-container&quot;]/i[@class=&quot;icon-close close&quot;]</value>
      <webElementGuid>3ed806d2-e19b-415d-ab87-10df166cafa0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div[2]/div/i</value>
      <webElementGuid>68f5dfbf-cb65-4394-80dc-de9cbaf974d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/i</value>
      <webElementGuid>202e3e4d-6dc2-4189-92c3-c2d3508794c4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
