<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>variants-normalizedColor-Azul-Claro</name>
   <tag></tag>
   <elementGuidId>b9c3e1c1-6496-4d73-ae4d-7d6a225777de</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#variants-normalizedColor-Azul-Claro</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
