<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>variants-normalizedColor-Morado</name>
   <tag></tag>
   <elementGuidId>c428c0c5-093f-41ef-97ea-1b066e682bc9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#variants-normalizedColor-Morado</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
